# Generated by Django 3.2 on 2025-03-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=1000)),
                ('measuring_unit', models.CharField(max_length=50)),
                ('GWP_factor', models.IntegerField()),
                ('scope', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '[esg].[attributes]',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('descr', models.TextField()),
            ],
            options={
                'db_table': 'entity',
            },
        ),
        migrations.CreateModel(
            name='ESGStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_standard', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=4)),
                ('sector', models.CharField(max_length=100)),
                ('esg_component', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '[esg].[iso_standards]',
            },
        ),
    ]
