# Generated by Django 3.2 on 2025-03-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attributes',
            table='esg.attributes',
        ),
    ]
