# Generated by Django 3.2 on 2025-03-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_attributes_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attributes',
            table='[esg].[attributes]',
        ),
    ]
